# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana-oss:6.2.3
# Plugin for Nested Objects
RUN bin/kibana-plugin install https://github.com/ppadovani/KibanaNestedSupportPlugin/releases/download/6.2.3-1.0.6/nested-fields-support-6.2.3-1.0.6.zip
