# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
EXPOSE 9200
EXPOSE 9300

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu